INSERT INTO Cities (ZipCode, Name) VALUES('1001', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1002', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1003', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1004', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1005', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1006', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1007', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1008', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1009', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1010', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1011', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1012', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1013', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1014', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1015', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1016', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1017', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1018', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1019', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1020', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1021', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1022', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1023', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1024', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1025', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1026', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1045', 'Ufrankerede svarforsendelser')
INSERT INTO Cities (ZipCode, Name) VALUES('1050', 'Kongens Nytorv')
INSERT INTO Cities (ZipCode, Name) VALUES('1051', 'Nyhavn')
INSERT INTO Cities (ZipCode, Name) VALUES('1052', 'Herluf Trolles Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1053', 'Cort Adelers Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1054', 'Peder Skrams Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1055', 'Tordenskjoldsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1055', 'August Bournonvilles Passage')
INSERT INTO Cities (ZipCode, Name) VALUES('1056', 'Heibergsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1057', 'Holbergsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1058', 'Havnegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1059', 'Niels Juels Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1060', 'Holmens Kanal')
INSERT INTO Cities (ZipCode, Name) VALUES('1061', 'Ved Stranden')
INSERT INTO Cities (ZipCode, Name) VALUES('1062', 'Boldhusgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1063', 'Laksegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1064', 'Asylgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1065', 'Fortunstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1066', 'Admiralgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1067', 'Nikolaj Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1068', 'Nikolajgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1069', 'Bremerholm')
INSERT INTO Cities (ZipCode, Name) VALUES('1070', 'Vingårdstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1071', 'Dybensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1072', 'Lille Kirkestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1073', 'Store Kirkestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1074', 'Lille Kongensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1092', 'Holmens Kanal 2-12')
INSERT INTO Cities (ZipCode, Name) VALUES('1093', 'Havnegade 5')
INSERT INTO Cities (ZipCode, Name) VALUES('1095', 'Kongens Nytorv 13')
INSERT INTO Cities (ZipCode, Name) VALUES('1098', 'Esplanaden 50')
INSERT INTO Cities (ZipCode, Name) VALUES('1100', 'Østergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1101', 'Ny Østergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1102', 'Pistolstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1103', 'Hovedvagtsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1104', 'Ny Adelgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1105', 'Kristen Bernikows Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1106', 'Antonigade')
INSERT INTO Cities (ZipCode, Name) VALUES('1107', 'Grønnegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1110', 'Store Regnegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1111', 'Christian IX''s Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1112', 'Pilestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1113', 'Silkegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1114', 'Kronprinsensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1115', 'Klareboderne')
INSERT INTO Cities (ZipCode, Name) VALUES('1116', 'Møntergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1117', 'Gammel Mønt')
INSERT INTO Cities (ZipCode, Name) VALUES('1118', 'Sværtegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1119', 'Landemærket')
INSERT INTO Cities (ZipCode, Name) VALUES('1120', 'Vognmagergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1121', 'Lønporten')
INSERT INTO Cities (ZipCode, Name) VALUES('1122', 'Sjæleboderne')
INSERT INTO Cities (ZipCode, Name) VALUES('1123', 'Gothersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1124', 'Åbenrå')
INSERT INTO Cities (ZipCode, Name) VALUES('1125', 'Suhmsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1126', 'Pustervig')
INSERT INTO Cities (ZipCode, Name) VALUES('1127', 'Hauser Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1128', 'Hausergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1129', 'Sankt Gertruds Stræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1130', 'Rosenborggade')
INSERT INTO Cities (ZipCode, Name) VALUES('1131', 'Tornebuskegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1140', 'Møntergade 19')
INSERT INTO Cities (ZipCode, Name) VALUES('1147', 'Pilestræde 34')
INSERT INTO Cities (ZipCode, Name) VALUES('1148', 'Vognmagergade 11')
INSERT INTO Cities (ZipCode, Name) VALUES('1150', 'Købmagergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1151', 'Valkendorfsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1152', 'Løvstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1153', 'Niels Hemmingsens Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1154', 'Gråbrødretorv')
INSERT INTO Cities (ZipCode, Name) VALUES('1155', 'Kejsergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1156', 'Gråbrødrestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1157', 'Klosterstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1158', 'Skoubogade')
INSERT INTO Cities (ZipCode, Name) VALUES('1159', 'Skindergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1160', 'Amagertorv')
INSERT INTO Cities (ZipCode, Name) VALUES('1161', 'Vimmelskaftet')
INSERT INTO Cities (ZipCode, Name) VALUES('1162', 'Jorcks Passage')
INSERT INTO Cities (ZipCode, Name) VALUES('1164', 'Nygade')
INSERT INTO Cities (ZipCode, Name) VALUES('1165', 'Nørregade')
INSERT INTO Cities (ZipCode, Name) VALUES('1165', 'Sankt Petri Passage')
INSERT INTO Cities (ZipCode, Name) VALUES('1166', 'Dyrkøb')
INSERT INTO Cities (ZipCode, Name) VALUES('1167', 'Bispetorvet')
INSERT INTO Cities (ZipCode, Name) VALUES('1168', 'Frue Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1169', 'Store Kannikestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1170', 'Lille Kannikestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1171', 'Fiolstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1172', 'Krystalgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1173', 'Peder Hvitfeldts Stræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1174', 'Rosengården')
INSERT INTO Cities (ZipCode, Name) VALUES('1175', 'Kultorvet')
INSERT INTO Cities (ZipCode, Name) VALUES('1200', 'Højbro Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1201', 'Læderstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1202', 'Gammel Strand')
INSERT INTO Cities (ZipCode, Name) VALUES('1203', 'Nybrogade')
INSERT INTO Cities (ZipCode, Name) VALUES('1204', 'Magstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1205', 'Snaregade')
INSERT INTO Cities (ZipCode, Name) VALUES('1206', 'Naboløs')
INSERT INTO Cities (ZipCode, Name) VALUES('1207', 'Hyskenstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1208', 'Kompagnistræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1209', 'Badstuestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1210', 'Knabrostræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1211', 'Brolæggerstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1212', 'Vindebrogade')
INSERT INTO Cities (ZipCode, Name) VALUES('1213', 'Bertel Thorvaldsens Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1214', 'Tøjhusgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1215', 'Børsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1216', 'Slotsholmsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1217', 'Slotsholmsgade 1')
INSERT INTO Cities (ZipCode, Name) VALUES('1218', 'Christiansborg')
INSERT INTO Cities (ZipCode, Name) VALUES('1218', 'Christiansborg Ridebane')
INSERT INTO Cities (ZipCode, Name) VALUES('1218', 'Christiansborg Slotsplads')
INSERT INTO Cities (ZipCode, Name) VALUES('1218', 'Prins Jørgens Gård')
INSERT INTO Cities (ZipCode, Name) VALUES('1218', 'Proviantpassagen')
INSERT INTO Cities (ZipCode, Name) VALUES('1218', 'Rigsdagsgården')
INSERT INTO Cities (ZipCode, Name) VALUES('1219', 'Christians Brygge 1-5 og 8')
INSERT INTO Cities (ZipCode, Name) VALUES('1220', 'Frederiksholms Kanal')
INSERT INTO Cities (ZipCode, Name) VALUES('1221', 'Søren Kierkegaards Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1240', 'Christiansborg')
INSERT INTO Cities (ZipCode, Name) VALUES('1250', 'Sankt Annæ Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1251', 'Kvæsthusgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1252', 'Kvæsthusbroen')
INSERT INTO Cities (ZipCode, Name) VALUES('1253', 'Toldbodgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1254', 'Lille Strandstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1255', 'Store Strandstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1256', 'Amaliegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1257', 'Amalienborg')
INSERT INTO Cities (ZipCode, Name) VALUES('1259', 'Nordre Toldbod')
INSERT INTO Cities (ZipCode, Name) VALUES('1259', 'Trekroner')
INSERT INTO Cities (ZipCode, Name) VALUES('1260', 'Bredgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1261', 'Palægade')
INSERT INTO Cities (ZipCode, Name) VALUES('1263', 'Churchillparken')
INSERT INTO Cities (ZipCode, Name) VALUES('1263', 'Esplanaden')
INSERT INTO Cities (ZipCode, Name) VALUES('1264', 'Store Kongensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1265', 'Frederiksgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1266', 'Bornholmsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1267', 'Hammerensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1268', 'Jens Kofods Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1270', 'Grønningen')
INSERT INTO Cities (ZipCode, Name) VALUES('1271', 'Poul Ankers Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1300', 'Borgergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1301', 'Landgreven')
INSERT INTO Cities (ZipCode, Name) VALUES('1302', 'Dronningens Tværgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1303', 'Hindegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1304', 'Adelgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1306', 'Kronprinsessegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1307', 'Georg Brandes Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1307', 'Sølvgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1308', 'Klerkegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1309', 'Rosengade')
INSERT INTO Cities (ZipCode, Name) VALUES('1310', 'Fredericiagade')
INSERT INTO Cities (ZipCode, Name) VALUES('1311', 'Olfert Fischers Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1312', 'Gammelvagt')
INSERT INTO Cities (ZipCode, Name) VALUES('1313', 'Sankt Pauls Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1314', 'Sankt Pauls Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1315', 'Rævegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1316', 'Rigensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1317', 'Stokhusgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1318', 'Krusemyntegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1319', 'Gernersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1320', 'Haregade')
INSERT INTO Cities (ZipCode, Name) VALUES('1321', 'Tigergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1322', 'Suensonsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1323', 'Hjertensfrydsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1324', 'Elsdyrsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1325', 'Delfingade')
INSERT INTO Cities (ZipCode, Name) VALUES('1326', 'Krokodillegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1327', 'Vildandegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1328', 'Svanegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1329', 'Timiansgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1350', 'Øster Voldgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1352', 'Rørholmsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1353', 'Øster Farimagsgade 3-15 og 2')
INSERT INTO Cities (ZipCode, Name) VALUES('1354', 'Ole Suhrs Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1355', 'Gammeltoftsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1356', 'Bartholinsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1357', 'Øster Søgade 8-36')
INSERT INTO Cities (ZipCode, Name) VALUES('1358', 'Nørre Voldgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1359', 'Ahlefeldtsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1359', 'Charlotte Ammundsens Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1360', 'Frederiksborggade')
INSERT INTO Cities (ZipCode, Name) VALUES('1361', 'Israels Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1361', 'Linnésgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1362', 'Rømersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1363', 'Vendersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1364', 'Nørre Farimagsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1365', 'Schacksgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1366', 'Nansensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1367', 'Kjeld Langes Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1368', 'Turesensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1369', 'Gyldenløvesgade lige nr.')
INSERT INTO Cities (ZipCode, Name) VALUES('1370', 'Nørre Søgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1371', 'Søtorvet')
INSERT INTO Cities (ZipCode, Name) VALUES('1400', 'Knippelsbro')
INSERT INTO Cities (ZipCode, Name) VALUES('1400', 'Torvegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1401', 'Strandgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1402', 'Asiatisk Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1402', 'David Balfours Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1402', 'Hammershøi Kaj')
INSERT INTO Cities (ZipCode, Name) VALUES('1402', 'Johan Semps Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1402', 'Nicolai Eigtveds Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1403', 'Wilders Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1406', 'Christianshavns Kanal')
INSERT INTO Cities (ZipCode, Name) VALUES('1407', 'Bådsmandsstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1408', 'Wildersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1409', 'Knippelsbrogade')
INSERT INTO Cities (ZipCode, Name) VALUES('1410', 'Christianshavns Torv')
INSERT INTO Cities (ZipCode, Name) VALUES('1411', 'Langebrogade')
INSERT INTO Cities (ZipCode, Name) VALUES('1411', 'Applebys Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1412', 'Voldgården')
INSERT INTO Cities (ZipCode, Name) VALUES('1413', 'Ved Kanalen')
INSERT INTO Cities (ZipCode, Name) VALUES('1414', 'Overgaden Neden Vandet')
INSERT INTO Cities (ZipCode, Name) VALUES('1415', 'Overgaden Oven Vandet')
INSERT INTO Cities (ZipCode, Name) VALUES('1416', 'Sankt Annæ Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1417', 'Mikkel Vibes Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1418', 'Sofiegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1419', 'Store Søndervoldstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1420', 'Dronningensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1421', 'Lille Søndervoldstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1422', 'Prinsessegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1423', 'Amagergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1424', 'Christianshavns Voldgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1425', 'Ved Volden')
INSERT INTO Cities (ZipCode, Name) VALUES('1426', 'Voldboligerne')
INSERT INTO Cities (ZipCode, Name) VALUES('1427', 'Brobergsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1428', 'Andreas Bjørns Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1429', 'Burmeistersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1430', 'Bodenhoffs Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1432', 'Margretheholmsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1432', 'Refshalevej')
INSERT INTO Cities (ZipCode, Name) VALUES('1432', 'William Wains Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1433', 'Christiansholms Ø')
INSERT INTO Cities (ZipCode, Name) VALUES('1433', 'Flakfortet')
INSERT INTO Cities (ZipCode, Name) VALUES('1433', 'Lynetten')
INSERT INTO Cities (ZipCode, Name) VALUES('1433', 'Margretheholm')
INSERT INTO Cities (ZipCode, Name) VALUES('1433', 'Middelgrundsfortet')
INSERT INTO Cities (ZipCode, Name) VALUES('1433', 'Quintus')
INSERT INTO Cities (ZipCode, Name) VALUES('1433', 'Refshaleøen')
INSERT INTO Cities (ZipCode, Name) VALUES('1434', 'Danneskiold-Samsøes Allé')
INSERT INTO Cities (ZipCode, Name) VALUES('1434', 'Kuglegårdsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1435', 'Philip De Langes Allé')
INSERT INTO Cities (ZipCode, Name) VALUES('1436', 'Arsenalvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1436', 'Halvtolv')
INSERT INTO Cities (ZipCode, Name) VALUES('1436', 'Kuglegården')
INSERT INTO Cities (ZipCode, Name) VALUES('1436', 'Søartillerivej')
INSERT INTO Cities (ZipCode, Name) VALUES('1436', 'Trangravsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1436', 'Værftsbroen')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Bohlendachvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Eik Skaløes Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Fabrikmestervej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Galionsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Kanonbådsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Leo Mathisens Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Masteskursvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Per Knutzons Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Schifters Kvarter')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Stibolts Kvarter')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Takkelloftsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1437', 'Theodor Christensens Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1438', 'Benstrups Kvarter')
INSERT INTO Cities (ZipCode, Name) VALUES('1438', 'Dokøvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1438', 'Ekvipagemestervej')
INSERT INTO Cities (ZipCode, Name) VALUES('1438', 'Judichærs Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1438', 'Orlogsværftvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'A.H. Vedels Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Bradbænken')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Elefanten')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Eskadrevej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'H.C. Sneedorffs Allé')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Henrik Gerners Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Henrik Spans Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Kongebrovej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Krudtløbsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Minørvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'P. Løvenørns Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Spanteloftvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Takkeladsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Ved Sixtusbatteriet')
INSERT INTO Cities (ZipCode, Name) VALUES('1439', 'Ved Søminegraven')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Bjørnekloen')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Blå Karamel')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Fabriksområdet')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Fredens Ark')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Løvehuset')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Mælkebøtten')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Mælkevejen')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Nordområdet')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Psyak')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Sydområdet')
INSERT INTO Cities (ZipCode, Name) VALUES('1440', 'Tinghuset')
INSERT INTO Cities (ZipCode, Name) VALUES('1441', 'Midtdyssen')
INSERT INTO Cities (ZipCode, Name) VALUES('1441', 'Norddyssen')
INSERT INTO Cities (ZipCode, Name) VALUES('1441', 'Syddyssen')
INSERT INTO Cities (ZipCode, Name) VALUES('1448', 'Asiatisk Plads 2')
INSERT INTO Cities (ZipCode, Name) VALUES('1450', 'Nytorv')
INSERT INTO Cities (ZipCode, Name) VALUES('1451', 'Larslejsstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1452', 'Teglgårdstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1453', 'Sankt Peders Stræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1454', 'Larsbjørnsstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1455', 'Studiestræde 3-49 og 6-40')
INSERT INTO Cities (ZipCode, Name) VALUES('1456', 'Vestergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1457', 'Gammeltorv')
INSERT INTO Cities (ZipCode, Name) VALUES('1458', 'Kattesundet')
INSERT INTO Cities (ZipCode, Name) VALUES('1459', 'Frederiksberggade')
INSERT INTO Cities (ZipCode, Name) VALUES('1460', 'Mikkel Bryggers Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1461', 'Slutterigade')
INSERT INTO Cities (ZipCode, Name) VALUES('1462', 'Lavendelstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1463', 'Farvergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1464', 'Hestemøllestræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1465', 'Gåsegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1466', 'Rådhusstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1467', 'Vandkunsten')
INSERT INTO Cities (ZipCode, Name) VALUES('1468', 'Løngangstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1470', 'Stormgade 2-14')
INSERT INTO Cities (ZipCode, Name) VALUES('1471', 'Ny Vestergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1472', 'Ny Kongensgade 1-15 og 4-14')
INSERT INTO Cities (ZipCode, Name) VALUES('1473', 'Bryghusgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1500', 'Carsten Niebuhrs Gade 4')
INSERT INTO Cities (ZipCode, Name) VALUES('1501', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1502', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1503', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1504', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1505', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1506', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1507', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1508', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1509', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1510', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1512', 'Carsten Niebuhrs Gade 4')
INSERT INTO Cities (ZipCode, Name) VALUES('1513', '')
INSERT INTO Cities (ZipCode, Name) VALUES('1532', 'Kystvejen 26, 2770 Kastrup')
INSERT INTO Cities (ZipCode, Name) VALUES('1533', 'Kystvejen 26, 2770 Kastrup')
INSERT INTO Cities (ZipCode, Name) VALUES('1550', 'Bag Rådhuset')
INSERT INTO Cities (ZipCode, Name) VALUES('1550', 'Rådhuspladsen')
INSERT INTO Cities (ZipCode, Name) VALUES('1551', 'Jarmers Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1552', 'Vester Voldgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1553', 'H.C. Andersens Boulevard')
INSERT INTO Cities (ZipCode, Name) VALUES('1553', 'Langebro')
INSERT INTO Cities (ZipCode, Name) VALUES('1554', 'Studiestræde 57-69 og 50-54')
INSERT INTO Cities (ZipCode, Name) VALUES('1555', 'Stormgade 20 og 35')
INSERT INTO Cities (ZipCode, Name) VALUES('1556', 'Dantes Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1557', 'Ny Kongensgade 19-21 og 18-20')
INSERT INTO Cities (ZipCode, Name) VALUES('1558', 'Christiansborggade')
INSERT INTO Cities (ZipCode, Name) VALUES('1559', 'Christians Brygge 24-30')
INSERT INTO Cities (ZipCode, Name) VALUES('1560', 'Kalvebod Brygge')
INSERT INTO Cities (ZipCode, Name) VALUES('1561', 'Fisketorvet')
INSERT INTO Cities (ZipCode, Name) VALUES('1561', 'Kalvebod Pladsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1562', 'Hambrosgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1563', 'Otto Mønsteds Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1564', 'Rysensteensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1567', 'Polititorvet')
INSERT INTO Cities (ZipCode, Name) VALUES('1568', 'Mitchellsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1569', 'Edvard Falcks Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1570', 'Banegårdspladsen')
INSERT INTO Cities (ZipCode, Name) VALUES('1570', 'Københavns Hovedbanegård')
INSERT INTO Cities (ZipCode, Name) VALUES('1571', 'Otto Mønsteds Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1572', 'Anker Heegaards Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1573', 'Puggaardsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1574', 'Niels Brocks Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1575', 'Ved Glyptoteket')
INSERT INTO Cities (ZipCode, Name) VALUES('1576', 'Stoltenbergsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1577', 'Arni Magnussons Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1577', 'Carsten Niebuhrs Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1577', 'Bernstorffsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1592', 'Bernstorffsgade 17-19')
INSERT INTO Cities (ZipCode, Name) VALUES('1599', 'Rådhuspladsen 1 ')
INSERT INTO Cities (ZipCode, Name) VALUES('1600', 'Gyldenløvesgade ulige nr.')
INSERT INTO Cities (ZipCode, Name) VALUES('1601', 'Vester Søgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1602', 'Nyropsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1603', 'Dahlerupsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1604', 'Kampmannsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1605', 'Herholdtsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1606', 'Vester Farimagsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1607', 'Staunings Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1608', 'Jernbanegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1609', 'Axeltorv')
INSERT INTO Cities (ZipCode, Name) VALUES('1610', 'Gammel Kongevej 1-55 og 10')
INSERT INTO Cities (ZipCode, Name) VALUES('1611', 'Hammerichsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1612', 'Ved Vesterport')
INSERT INTO Cities (ZipCode, Name) VALUES('1613', 'Meldahlsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1614', 'Trommesalen')
INSERT INTO Cities (ZipCode, Name) VALUES('1615', 'Sankt Jørgens Allé')
INSERT INTO Cities (ZipCode, Name) VALUES('1616', 'Stenosgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1617', 'Bagerstræde')
INSERT INTO Cities (ZipCode, Name) VALUES('1618', 'Tullinsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1619', 'Værnedamsvej lige nr.')
INSERT INTO Cities (ZipCode, Name) VALUES('1620', 'Vesterbrogade 1-149 og 2-150')
INSERT INTO Cities (ZipCode, Name) VALUES('1620', 'Vesterbros Torv')
INSERT INTO Cities (ZipCode, Name) VALUES('1621', 'Frederiksberg Alle 1 - 13B')
INSERT INTO Cities (ZipCode, Name) VALUES('1622', 'Boyesgade ulige nr')
INSERT INTO Cities (ZipCode, Name) VALUES('1623', 'Kingosgade 1-9')
INSERT INTO Cities (ZipCode, Name) VALUES('1624', 'Brorsonsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1630', 'Vesterbrogade 3')
INSERT INTO Cities (ZipCode, Name) VALUES('1631', 'Herman Triers Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1632', 'Julius Thomsens Gade lige nr')
INSERT INTO Cities (ZipCode, Name) VALUES('1633', 'Kleinsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1634', 'Rosenørns Allé 2-18')
INSERT INTO Cities (ZipCode, Name) VALUES('1635', 'Åboulevard 1-13')
INSERT INTO Cities (ZipCode, Name) VALUES('1650', 'Istedgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1651', 'Reventlowsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1652', 'Colbjørnsensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1653', 'Helgolandsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1654', 'Abel Cathrines Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1655', 'Viktoriagade')
INSERT INTO Cities (ZipCode, Name) VALUES('1656', 'Gasværksvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1657', 'Eskildsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1658', 'Absalonsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1659', 'Svendsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1660', 'Dannebrogsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1660', 'Otto Krabbes Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1661', 'Westend')
INSERT INTO Cities (ZipCode, Name) VALUES('1662', 'Saxogade')
INSERT INTO Cities (ZipCode, Name) VALUES('1663', 'Oehlenschlægersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1664', 'Kaalundsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1665', 'Valdemarsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1666', 'Matthæusgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1667', 'Frederiksstadsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1668', 'Mysundegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1669', 'Flensborggade')
INSERT INTO Cities (ZipCode, Name) VALUES('1670', 'Enghave Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1671', 'Haderslevgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1671', 'Tove Ditlevsens Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1672', 'Broagergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1673', 'Ullerupgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1674', 'Enghavevej 1-77 og 2-78')
INSERT INTO Cities (ZipCode, Name) VALUES('1675', 'Kongshøjgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1676', 'Sankelmarksgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1677', 'Gråstensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1699', 'Staldgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1700', 'Halmtorvet')
INSERT INTO Cities (ZipCode, Name) VALUES('1701', 'Reverdilsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1702', 'Stampesgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1703', 'Lille Colbjørnsensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1704', 'Tietgensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1705', 'Ingerslevsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1706', 'Lille Istedgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1707', 'Maria Kirkeplads')
INSERT INTO Cities (ZipCode, Name) VALUES('1708', 'Eriksgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1709', 'Skydebanegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1710', 'Kvægtorvsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1711', 'Flæsketorvet')
INSERT INTO Cities (ZipCode, Name) VALUES('1711', 'Onkel Dannys Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1712', 'Høkerboderne')
INSERT INTO Cities (ZipCode, Name) VALUES('1714', 'Kødboderne')
INSERT INTO Cities (ZipCode, Name) VALUES('1715', 'Slagtehusgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1716', 'Slagterboderne')
INSERT INTO Cities (ZipCode, Name) VALUES('1717', 'Skelbækgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1718', 'Sommerstedgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1719', 'Krusågade')
INSERT INTO Cities (ZipCode, Name) VALUES('1720', 'Sønder Boulevard')
INSERT INTO Cities (ZipCode, Name) VALUES('1721', 'Dybbølsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1722', 'Godsbanegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1723', 'Letlandsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1724', 'Estlandsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1725', 'Esbern Snares Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1726', 'Arkonagade')
INSERT INTO Cities (ZipCode, Name) VALUES('1727', 'Asger Rygs Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1728', 'Skjalm Hvides Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1729', 'Sigerstedgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1730', 'Knud Lavards Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1731', 'Erik Ejegods Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1732', 'Bodilsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1733', 'Palnatokesgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1734', 'Heilsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1735', 'Røddinggade')
INSERT INTO Cities (ZipCode, Name) VALUES('1736', 'Bevtoftgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1737', 'Bustrupgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1738', 'Stenderupgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1739', 'Enghave Passage')
INSERT INTO Cities (ZipCode, Name) VALUES('1749', 'Rahbeks Allé 3-11')
INSERT INTO Cities (ZipCode, Name) VALUES('1750', 'Vesterfælledvej 1-9 og 2-56')
INSERT INTO Cities (ZipCode, Name) VALUES('1751', 'Sundevedsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1752', 'Tøndergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1753', 'Ballumgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1754', 'Hedebygade')
INSERT INTO Cities (ZipCode, Name) VALUES('1755', 'Møgeltøndergade')
INSERT INTO Cities (ZipCode, Name) VALUES('1756', 'Amerikavej')
INSERT INTO Cities (ZipCode, Name) VALUES('1757', 'Trøjborggade')
INSERT INTO Cities (ZipCode, Name) VALUES('1758', 'Lyrskovgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1759', 'Rejsbygade')
INSERT INTO Cities (ZipCode, Name) VALUES('1760', 'Ny Carlsberg Vej 1-37 og 2-66')
INSERT INTO Cities (ZipCode, Name) VALUES('1761', 'Ejderstedgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1762', 'Slesvigsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1763', 'Dannevirkegade')
INSERT INTO Cities (ZipCode, Name) VALUES('1764', 'Alsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1765', 'Angelgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1766', 'Slien')
INSERT INTO Cities (ZipCode, Name) VALUES('1770', 'Carstensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1771', 'Lundbyesgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1772', 'Ernst Meyers Gade')
INSERT INTO Cities (ZipCode, Name) VALUES('1773', 'Bissensgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1774', 'Küchlersgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1775', 'Freundsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1777', 'Jerichausgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1780', '')
INSERT INTO Cities (ZipCode, Name) VALUES('1782', 'Ufrankerede svarforsendelser')
INSERT INTO Cities (ZipCode, Name) VALUES('1785', 'Rådhuspladsen 33 og 37')
INSERT INTO Cities (ZipCode, Name) VALUES('1786', 'Vesterbrogade 8')
INSERT INTO Cities (ZipCode, Name) VALUES('1787', 'H.C. Andersens Boulevard 18')
INSERT INTO Cities (ZipCode, Name) VALUES('1790', '')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Bag Elefanterne')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Banevolden 2')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Bjerregårdsvej 5 og 7')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Bryggernes Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Gamle Carlsberg Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Kammasvej 2, 4 og 6')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Ny Carlsberg Vej fra 39 og fra 68')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Ottilia Jacobsens Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Pasteursvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Rahbeks Allé 13-15')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Valby Langgade 1')
INSERT INTO Cities (ZipCode, Name) VALUES('1799', 'Vesterfælledvej 58-110')
INSERT INTO Cities (ZipCode, Name) VALUES('1800', 'Vesterbrogade 161-191 og 162-208')
INSERT INTO Cities (ZipCode, Name) VALUES('1801', 'Rahbeks Alle 2-36')
INSERT INTO Cities (ZipCode, Name) VALUES('1802', 'Halls Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1803', 'Brøndsteds Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1804', 'Bakkegårds Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1805', 'Kammasvej 3')
INSERT INTO Cities (ZipCode, Name) VALUES('1806', 'Jacobys Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1807', 'Schlegels Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1808', 'Asmussens Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1809', 'Frydendalsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1810', 'Platanvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1811', 'Asgårdsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1812', 'Kochsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1813', 'Henrik Ibsens Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1814', 'Carit Etlars Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1815', 'Paludan Müllers Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1816', 'Engtoftevej')
INSERT INTO Cities (ZipCode, Name) VALUES('1817', 'Carl Bernhards Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1818', 'Kingosgade 11-17 og 8-10')
INSERT INTO Cities (ZipCode, Name) VALUES('1819', 'Værnedamsvej ulige nr.')
INSERT INTO Cities (ZipCode, Name) VALUES('1820', 'Frederiksberg Alle 15-63 og 2-104')
INSERT INTO Cities (ZipCode, Name) VALUES('1822', 'Boyesgade lige nr.')
INSERT INTO Cities (ZipCode, Name) VALUES('1823', 'Haveselskabetsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1824', 'Sankt Thomas Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1825', 'Hauchsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1826', 'Alhambravej')
INSERT INTO Cities (ZipCode, Name) VALUES('1827', 'Mynstersvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1828', 'Martensens Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1829', 'Madvigs Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1835', 'Postboks')
INSERT INTO Cities (ZipCode, Name) VALUES('1850', 'Gammel Kongevej 85-179 og 60-178')
INSERT INTO Cities (ZipCode, Name) VALUES('1851', 'Nyvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1852', 'Amicisvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1853', 'Maglekildevej')
INSERT INTO Cities (ZipCode, Name) VALUES('1854', 'Dr. Priemes Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1855', 'Hollændervej')
INSERT INTO Cities (ZipCode, Name) VALUES('1856', 'Edisonsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1857', 'Hortensiavej')
INSERT INTO Cities (ZipCode, Name) VALUES('1860', 'Christian Winthers Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1861', 'Sagasvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1862', 'Rathsacksvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1863', 'Ceresvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1864', 'Grundtvigsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1865', 'Grundtvigs Sidevej')
INSERT INTO Cities (ZipCode, Name) VALUES('1866', 'Henrik Steffens Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1867', 'Acaciavej')
INSERT INTO Cities (ZipCode, Name) VALUES('1868', 'Bianco Lunos Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1870', 'Bülowsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1871', 'Thorvaldsensvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1872', 'Bomhoffs Have')
INSERT INTO Cities (ZipCode, Name) VALUES('1873', 'Helenevej')
INSERT INTO Cities (ZipCode, Name) VALUES('1874', 'Harsdorffsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1875', 'Amalievej')
INSERT INTO Cities (ZipCode, Name) VALUES('1876', 'Kastanievej')
INSERT INTO Cities (ZipCode, Name) VALUES('1877', 'Lindevej')
INSERT INTO Cities (ZipCode, Name) VALUES('1878', 'Uraniavej')
INSERT INTO Cities (ZipCode, Name) VALUES('1879', 'H.C. Ørsteds Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1900', 'Vodroffsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1901', 'Tårnborgvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1902', 'Lykkesholms Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1903', 'Sankt Knuds Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1904', 'Forhåbningsholms Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1905', 'Svanholmsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1906', 'Schønbergsgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1908', 'Prinsesse Maries Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1909', 'Vodroffs Tværgade')
INSERT INTO Cities (ZipCode, Name) VALUES('1910', 'Danasvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1911', 'Niels Ebbesens Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1912', 'Svend Trøsts Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1913', 'Carl Plougs Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1914', 'Vodroffslund')
INSERT INTO Cities (ZipCode, Name) VALUES('1915', 'Danas Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1916', 'Norsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1917', 'Sveasvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1920', 'Forchhammersvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1921', 'Sankt Markus Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1922', 'Sankt Markus Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1923', 'Johnstrups Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1924', 'Steenstrups Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1925', 'Julius Thomsens Plads')
INSERT INTO Cities (ZipCode, Name) VALUES('1926', 'Martinsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1927', 'Suomisvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1928', 'Filippavej')
INSERT INTO Cities (ZipCode, Name) VALUES('1931', 'Ufrankerede svarforsendelser ')
INSERT INTO Cities (ZipCode, Name) VALUES('1950', 'Hostrupsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1951', 'Christian Richardts Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1952', 'Falkonervænget')
INSERT INTO Cities (ZipCode, Name) VALUES('1953', 'Sankt Nikolaj Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1954', 'Hostrups Have')
INSERT INTO Cities (ZipCode, Name) VALUES('1955', 'Dr. Abildgaards Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1956', 'L.I. Brandes Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1957', 'N.J. Fjords Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1958', 'Rolighedsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1959', 'Falkonergårdsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1960', 'Åboulevard 15-55')
INSERT INTO Cities (ZipCode, Name) VALUES('1961', 'J.M. Thieles Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1962', 'Fuglevangsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1963', 'Bille Brahes Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1964', 'Ingemannsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1965', 'Erik Menveds Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1966', 'Steenwinkelsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1967', 'Svanemosegårdsvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1970', 'Rosenørns Alle 1-67 og 22-70')
INSERT INTO Cities (ZipCode, Name) VALUES('1971', 'Adolph Steens Alle')
INSERT INTO Cities (ZipCode, Name) VALUES('1972', 'Worsaaesvej')
INSERT INTO Cities (ZipCode, Name) VALUES('1973', 'Jakob Dannefærds Vej')
INSERT INTO Cities (ZipCode, Name) VALUES('1974', 'Julius Thomsens Gade ulige nr.')
INSERT INTO Cities (ZipCode, Name) VALUES('2000', 'Frederiksberg')
INSERT INTO Cities (ZipCode, Name) VALUES('2100', 'København Ø')
INSERT INTO Cities (ZipCode, Name) VALUES('2150', 'Nordhavn')
INSERT INTO Cities (ZipCode, Name) VALUES('2200', 'København N')
INSERT INTO Cities (ZipCode, Name) VALUES('2300', 'København S')
INSERT INTO Cities (ZipCode, Name) VALUES('2400', 'København NV')
INSERT INTO Cities (ZipCode, Name) VALUES('2412', 'Grønland')
INSERT INTO Cities (ZipCode, Name) VALUES('2450', 'København SV')
INSERT INTO Cities (ZipCode, Name) VALUES('2500', 'Valby')
INSERT INTO Cities (ZipCode, Name) VALUES('2600', 'Glostrup')
INSERT INTO Cities (ZipCode, Name) VALUES('2605', 'Brøndby')
INSERT INTO Cities (ZipCode, Name) VALUES('2610', 'Rødovre')
INSERT INTO Cities (ZipCode, Name) VALUES('2620', 'Albertslund')
INSERT INTO Cities (ZipCode, Name) VALUES('2625', 'Vallensbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('2630', 'Taastrup')
INSERT INTO Cities (ZipCode, Name) VALUES('2635', 'Ishøj')
INSERT INTO Cities (ZipCode, Name) VALUES('2640', 'Hedehusene')
INSERT INTO Cities (ZipCode, Name) VALUES('2650', 'Hvidovre')
INSERT INTO Cities (ZipCode, Name) VALUES('2660', 'Brøndby Strand')
INSERT INTO Cities (ZipCode, Name) VALUES('2665', 'Vallensbæk Strand')
INSERT INTO Cities (ZipCode, Name) VALUES('2670', 'Greve')
INSERT INTO Cities (ZipCode, Name) VALUES('2680', 'Solrød Strand')
INSERT INTO Cities (ZipCode, Name) VALUES('2690', 'Karlslunde')
INSERT INTO Cities (ZipCode, Name) VALUES('2700', 'Brønshøj')
INSERT INTO Cities (ZipCode, Name) VALUES('2720', 'Vanløse')
INSERT INTO Cities (ZipCode, Name) VALUES('2730', 'Herlev')
INSERT INTO Cities (ZipCode, Name) VALUES('2740', 'Skovlunde')
INSERT INTO Cities (ZipCode, Name) VALUES('2750', 'Ballerup')
INSERT INTO Cities (ZipCode, Name) VALUES('2760', 'Måløv')
INSERT INTO Cities (ZipCode, Name) VALUES('2765', 'Smørum')
INSERT INTO Cities (ZipCode, Name) VALUES('2770', 'Kastrup')
INSERT INTO Cities (ZipCode, Name) VALUES('2791', 'Dragør')
INSERT INTO Cities (ZipCode, Name) VALUES('2800', 'Kongens Lyngby')
INSERT INTO Cities (ZipCode, Name) VALUES('2820', 'Gentofte')
INSERT INTO Cities (ZipCode, Name) VALUES('2830', 'Virum')
INSERT INTO Cities (ZipCode, Name) VALUES('2840', 'Holte')
INSERT INTO Cities (ZipCode, Name) VALUES('2850', 'Nærum')
INSERT INTO Cities (ZipCode, Name) VALUES('2860', 'Søborg')
INSERT INTO Cities (ZipCode, Name) VALUES('2870', 'Dyssegård')
INSERT INTO Cities (ZipCode, Name) VALUES('2880', 'Bagsværd')
INSERT INTO Cities (ZipCode, Name) VALUES('2900', 'Hellerup')
INSERT INTO Cities (ZipCode, Name) VALUES('2920', 'Charlottenlund')
INSERT INTO Cities (ZipCode, Name) VALUES('2930', 'Klampenborg')
INSERT INTO Cities (ZipCode, Name) VALUES('2942', 'Skodsborg')
INSERT INTO Cities (ZipCode, Name) VALUES('2950', 'Vedbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('2960', 'Rungsted Kyst')
INSERT INTO Cities (ZipCode, Name) VALUES('2970', 'Hørsholm')
INSERT INTO Cities (ZipCode, Name) VALUES('2980', 'Kokkedal')
INSERT INTO Cities (ZipCode, Name) VALUES('2990', 'Nivå')
INSERT INTO Cities (ZipCode, Name) VALUES('3000', 'Helsingør')
INSERT INTO Cities (ZipCode, Name) VALUES('3050', 'Humlebæk')
INSERT INTO Cities (ZipCode, Name) VALUES('3060', 'Espergærde')
INSERT INTO Cities (ZipCode, Name) VALUES('3070', 'Snekkersten')
INSERT INTO Cities (ZipCode, Name) VALUES('3080', 'Tikøb')
INSERT INTO Cities (ZipCode, Name) VALUES('3100', 'Hornbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('3120', 'Dronningmølle')
INSERT INTO Cities (ZipCode, Name) VALUES('3140', 'Ålsgårde')
INSERT INTO Cities (ZipCode, Name) VALUES('3150', 'Hellebæk')
INSERT INTO Cities (ZipCode, Name) VALUES('3200', 'Helsinge')
INSERT INTO Cities (ZipCode, Name) VALUES('3210', 'Vejby')
INSERT INTO Cities (ZipCode, Name) VALUES('3220', 'Tisvildeleje')
INSERT INTO Cities (ZipCode, Name) VALUES('3230', 'Græsted')
INSERT INTO Cities (ZipCode, Name) VALUES('3250', 'Gilleleje')
INSERT INTO Cities (ZipCode, Name) VALUES('3300', 'Frederiksværk')
INSERT INTO Cities (ZipCode, Name) VALUES('3310', 'Ølsted')
INSERT INTO Cities (ZipCode, Name) VALUES('3320', 'Skævinge')
INSERT INTO Cities (ZipCode, Name) VALUES('3330', 'Gørløse')
INSERT INTO Cities (ZipCode, Name) VALUES('3360', 'Liseleje')
INSERT INTO Cities (ZipCode, Name) VALUES('3370', 'Melby')
INSERT INTO Cities (ZipCode, Name) VALUES('3390', 'Hundested')
INSERT INTO Cities (ZipCode, Name) VALUES('3400', 'Hillerød')
INSERT INTO Cities (ZipCode, Name) VALUES('3450', 'Allerød')
INSERT INTO Cities (ZipCode, Name) VALUES('3460', 'Birkerød')
INSERT INTO Cities (ZipCode, Name) VALUES('3480', 'Fredensborg')
INSERT INTO Cities (ZipCode, Name) VALUES('3490', 'Kvistgård')
INSERT INTO Cities (ZipCode, Name) VALUES('3500', 'Værløse')
INSERT INTO Cities (ZipCode, Name) VALUES('3520', 'Farum')
INSERT INTO Cities (ZipCode, Name) VALUES('3540', 'Lynge')
INSERT INTO Cities (ZipCode, Name) VALUES('3550', 'Slangerup')
INSERT INTO Cities (ZipCode, Name) VALUES('3600', 'Frederikssund')
INSERT INTO Cities (ZipCode, Name) VALUES('3630', 'Jægerspris')
INSERT INTO Cities (ZipCode, Name) VALUES('3650', 'Ølstykke')
INSERT INTO Cities (ZipCode, Name) VALUES('3660', 'Stenløse')
INSERT INTO Cities (ZipCode, Name) VALUES('3670', 'Veksø Sjælland')
INSERT INTO Cities (ZipCode, Name) VALUES('3700', 'Rønne')
INSERT INTO Cities (ZipCode, Name) VALUES('3720', 'Aakirkeby')
INSERT INTO Cities (ZipCode, Name) VALUES('3730', 'Nexø')
INSERT INTO Cities (ZipCode, Name) VALUES('3740', 'Svaneke')
INSERT INTO Cities (ZipCode, Name) VALUES('3751', 'Østermarie')
INSERT INTO Cities (ZipCode, Name) VALUES('3760', 'Gudhjem')
INSERT INTO Cities (ZipCode, Name) VALUES('3770', 'Allinge')
INSERT INTO Cities (ZipCode, Name) VALUES('3782', 'Klemensker')
INSERT INTO Cities (ZipCode, Name) VALUES('3790', 'Hasle')
INSERT INTO Cities (ZipCode, Name) VALUES('4000', 'Roskilde')
INSERT INTO Cities (ZipCode, Name) VALUES('4030', 'Tune')
INSERT INTO Cities (ZipCode, Name) VALUES('4040', 'Jyllinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4050', 'Skibby')
INSERT INTO Cities (ZipCode, Name) VALUES('4060', 'Kirke Såby')
INSERT INTO Cities (ZipCode, Name) VALUES('4070', 'Kirke Hyllinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4100', 'Ringsted')
INSERT INTO Cities (ZipCode, Name) VALUES('4129', 'Ringsted')
INSERT INTO Cities (ZipCode, Name) VALUES('4130', 'Viby Sjælland')
INSERT INTO Cities (ZipCode, Name) VALUES('4140', 'Borup')
INSERT INTO Cities (ZipCode, Name) VALUES('4160', 'Herlufmagle')
INSERT INTO Cities (ZipCode, Name) VALUES('4171', 'Glumsø')
INSERT INTO Cities (ZipCode, Name) VALUES('4173', 'Fjenneslev')
INSERT INTO Cities (ZipCode, Name) VALUES('4174', 'Jystrup Midtsj')
INSERT INTO Cities (ZipCode, Name) VALUES('4180', 'Sorø')
INSERT INTO Cities (ZipCode, Name) VALUES('4190', 'Munke Bjergby')
INSERT INTO Cities (ZipCode, Name) VALUES('4200', 'Slagelse')
INSERT INTO Cities (ZipCode, Name) VALUES('4220', 'Korsør')
INSERT INTO Cities (ZipCode, Name) VALUES('4230', 'Skælskør')
INSERT INTO Cities (ZipCode, Name) VALUES('4241', 'Vemmelev')
INSERT INTO Cities (ZipCode, Name) VALUES('4242', 'Boeslunde')
INSERT INTO Cities (ZipCode, Name) VALUES('4243', 'Rude')
INSERT INTO Cities (ZipCode, Name) VALUES('4244', 'Agersø')
INSERT INTO Cities (ZipCode, Name) VALUES('4245', 'Omø')
INSERT INTO Cities (ZipCode, Name) VALUES('4250', 'Fuglebjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('4261', 'Dalmose')
INSERT INTO Cities (ZipCode, Name) VALUES('4262', 'Sandved')
INSERT INTO Cities (ZipCode, Name) VALUES('4270', 'Høng')
INSERT INTO Cities (ZipCode, Name) VALUES('4281', 'Gørlev')
INSERT INTO Cities (ZipCode, Name) VALUES('4291', 'Ruds Vedby')
INSERT INTO Cities (ZipCode, Name) VALUES('4293', 'Dianalund')
INSERT INTO Cities (ZipCode, Name) VALUES('4295', 'Stenlille')
INSERT INTO Cities (ZipCode, Name) VALUES('4296', 'Nyrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4300', 'Holbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('4305', 'Orø')
INSERT INTO Cities (ZipCode, Name) VALUES('4320', 'Lejre')
INSERT INTO Cities (ZipCode, Name) VALUES('4330', 'Hvalsø')
INSERT INTO Cities (ZipCode, Name) VALUES('4340', 'Tølløse')
INSERT INTO Cities (ZipCode, Name) VALUES('4350', 'Ugerløse')
INSERT INTO Cities (ZipCode, Name) VALUES('4360', 'Kirke Eskilstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4370', 'Store Merløse')
INSERT INTO Cities (ZipCode, Name) VALUES('4390', 'Vipperød')
INSERT INTO Cities (ZipCode, Name) VALUES('4400', 'Kalundborg')
INSERT INTO Cities (ZipCode, Name) VALUES('4420', 'Regstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4440', 'Mørkøv')
INSERT INTO Cities (ZipCode, Name) VALUES('4450', 'Jyderup')
INSERT INTO Cities (ZipCode, Name) VALUES('4460', 'Snertinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4470', 'Svebølle')
INSERT INTO Cities (ZipCode, Name) VALUES('4480', 'Store Fuglede')
INSERT INTO Cities (ZipCode, Name) VALUES('4490', 'Jerslev Sjælland')
INSERT INTO Cities (ZipCode, Name) VALUES('4500', 'Nykøbing Sj')
INSERT INTO Cities (ZipCode, Name) VALUES('4520', 'Svinninge')
INSERT INTO Cities (ZipCode, Name) VALUES('4532', 'Gislinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4534', 'Hørve')
INSERT INTO Cities (ZipCode, Name) VALUES('4540', 'Fårevejle')
INSERT INTO Cities (ZipCode, Name) VALUES('4550', 'Asnæs')
INSERT INTO Cities (ZipCode, Name) VALUES('4560', 'Vig')
INSERT INTO Cities (ZipCode, Name) VALUES('4571', 'Grevinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4572', 'Nørre Asmindrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4573', 'Højby')
INSERT INTO Cities (ZipCode, Name) VALUES('4581', 'Rørvig')
INSERT INTO Cities (ZipCode, Name) VALUES('4583', 'Sjællands Odde')
INSERT INTO Cities (ZipCode, Name) VALUES('4591', 'Føllenslev')
INSERT INTO Cities (ZipCode, Name) VALUES('4592', 'Sejerø')
INSERT INTO Cities (ZipCode, Name) VALUES('4593', 'Eskebjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('4600', 'Køge')
INSERT INTO Cities (ZipCode, Name) VALUES('4621', 'Gadstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4622', 'Havdrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4623', 'Lille Skensved')
INSERT INTO Cities (ZipCode, Name) VALUES('4632', 'Bjæverskov')
INSERT INTO Cities (ZipCode, Name) VALUES('4640', 'Faxe')
INSERT INTO Cities (ZipCode, Name) VALUES('4652', 'Hårlev')
INSERT INTO Cities (ZipCode, Name) VALUES('4653', 'Karise')
INSERT INTO Cities (ZipCode, Name) VALUES('4654', 'Faxe Ladeplads')
INSERT INTO Cities (ZipCode, Name) VALUES('4660', 'Store Heddinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4671', 'Strøby')
INSERT INTO Cities (ZipCode, Name) VALUES('4672', 'Klippinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4673', 'Rødvig Stevns')
INSERT INTO Cities (ZipCode, Name) VALUES('4681', 'Herfølge')
INSERT INTO Cities (ZipCode, Name) VALUES('4682', 'Tureby')
INSERT INTO Cities (ZipCode, Name) VALUES('4683', 'Rønnede')
INSERT INTO Cities (ZipCode, Name) VALUES('4684', 'Holmegaard')
INSERT INTO Cities (ZipCode, Name) VALUES('4690', 'Haslev')
INSERT INTO Cities (ZipCode, Name) VALUES('4700', 'Næstved')
INSERT INTO Cities (ZipCode, Name) VALUES('4720', 'Præstø')
INSERT INTO Cities (ZipCode, Name) VALUES('4733', 'Tappernøje')
INSERT INTO Cities (ZipCode, Name) VALUES('4735', 'Mern')
INSERT INTO Cities (ZipCode, Name) VALUES('4736', 'Karrebæksminde')
INSERT INTO Cities (ZipCode, Name) VALUES('4750', 'Lundby')
INSERT INTO Cities (ZipCode, Name) VALUES('4760', 'Vordingborg')
INSERT INTO Cities (ZipCode, Name) VALUES('4771', 'Kalvehave')
INSERT INTO Cities (ZipCode, Name) VALUES('4772', 'Langebæk')
INSERT INTO Cities (ZipCode, Name) VALUES('4773', 'Stensved')
INSERT INTO Cities (ZipCode, Name) VALUES('4780', 'Stege')
INSERT INTO Cities (ZipCode, Name) VALUES('4791', 'Borre')
INSERT INTO Cities (ZipCode, Name) VALUES('4792', 'Askeby')
INSERT INTO Cities (ZipCode, Name) VALUES('4793', 'Bogø By')
INSERT INTO Cities (ZipCode, Name) VALUES('4800', 'Nykøbing F')
INSERT INTO Cities (ZipCode, Name) VALUES('4840', 'Nørre Alslev')
INSERT INTO Cities (ZipCode, Name) VALUES('4850', 'Stubbekøbing')
INSERT INTO Cities (ZipCode, Name) VALUES('4862', 'Guldborg')
INSERT INTO Cities (ZipCode, Name) VALUES('4863', 'Eskilstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4871', 'Horbelev')
INSERT INTO Cities (ZipCode, Name) VALUES('4872', 'Idestrup')
INSERT INTO Cities (ZipCode, Name) VALUES('4873', 'Væggerløse')
INSERT INTO Cities (ZipCode, Name) VALUES('4874', 'Gedser')
INSERT INTO Cities (ZipCode, Name) VALUES('4880', 'Nysted')
INSERT INTO Cities (ZipCode, Name) VALUES('4891', 'Toreby L')
INSERT INTO Cities (ZipCode, Name) VALUES('4892', 'Kettinge')
INSERT INTO Cities (ZipCode, Name) VALUES('4894', 'Øster Ulslev')
INSERT INTO Cities (ZipCode, Name) VALUES('4895', 'Errindlev')
INSERT INTO Cities (ZipCode, Name) VALUES('4900', 'Nakskov')
INSERT INTO Cities (ZipCode, Name) VALUES('4912', 'Harpelunde')
INSERT INTO Cities (ZipCode, Name) VALUES('4913', 'Horslunde')
INSERT INTO Cities (ZipCode, Name) VALUES('4920', 'Søllested')
INSERT INTO Cities (ZipCode, Name) VALUES('4930', 'Maribo')
INSERT INTO Cities (ZipCode, Name) VALUES('4941', 'Bandholm')
INSERT INTO Cities (ZipCode, Name) VALUES('4942', 'Askø og Lilleø')
INSERT INTO Cities (ZipCode, Name) VALUES('4943', 'Torrig L')
INSERT INTO Cities (ZipCode, Name) VALUES('4944', 'Fejø')
INSERT INTO Cities (ZipCode, Name) VALUES('4945', 'Femø')
INSERT INTO Cities (ZipCode, Name) VALUES('4951', 'Nørreballe')
INSERT INTO Cities (ZipCode, Name) VALUES('4952', 'Stokkemarke')
INSERT INTO Cities (ZipCode, Name) VALUES('4953', 'Vesterborg')
INSERT INTO Cities (ZipCode, Name) VALUES('4960', 'Holeby')
INSERT INTO Cities (ZipCode, Name) VALUES('4970', 'Rødby')
INSERT INTO Cities (ZipCode, Name) VALUES('4983', 'Dannemare')
INSERT INTO Cities (ZipCode, Name) VALUES('4990', 'Sakskøbing')
INSERT INTO Cities (ZipCode, Name) VALUES('4992', 'Midtsjælland USF P')
INSERT INTO Cities (ZipCode, Name) VALUES('5000', 'Odense C')
INSERT INTO Cities (ZipCode, Name) VALUES('5029', 'Odense C')
INSERT INTO Cities (ZipCode, Name) VALUES('5100', 'Odense C')
INSERT INTO Cities (ZipCode, Name) VALUES('5200', 'Odense V')
INSERT INTO Cities (ZipCode, Name) VALUES('5210', 'Odense NV')
INSERT INTO Cities (ZipCode, Name) VALUES('5220', 'Odense SØ')
INSERT INTO Cities (ZipCode, Name) VALUES('5230', 'Odense M')
INSERT INTO Cities (ZipCode, Name) VALUES('5240', 'Odense NØ')
INSERT INTO Cities (ZipCode, Name) VALUES('5250', 'Odense SV')
INSERT INTO Cities (ZipCode, Name) VALUES('5260', 'Odense S')
INSERT INTO Cities (ZipCode, Name) VALUES('5270', 'Odense N')
INSERT INTO Cities (ZipCode, Name) VALUES('5290', 'Marslev')
INSERT INTO Cities (ZipCode, Name) VALUES('5300', 'Kerteminde')
INSERT INTO Cities (ZipCode, Name) VALUES('5320', 'Agedrup')
INSERT INTO Cities (ZipCode, Name) VALUES('5330', 'Munkebo')
INSERT INTO Cities (ZipCode, Name) VALUES('5350', 'Rynkeby')
INSERT INTO Cities (ZipCode, Name) VALUES('5370', 'Mesinge')
INSERT INTO Cities (ZipCode, Name) VALUES('5380', 'Dalby')
INSERT INTO Cities (ZipCode, Name) VALUES('5390', 'Martofte')
INSERT INTO Cities (ZipCode, Name) VALUES('5400', 'Bogense')
INSERT INTO Cities (ZipCode, Name) VALUES('5450', 'Otterup')
INSERT INTO Cities (ZipCode, Name) VALUES('5462', 'Morud')
INSERT INTO Cities (ZipCode, Name) VALUES('5463', 'Harndrup')
INSERT INTO Cities (ZipCode, Name) VALUES('5464', 'Brenderup Fyn')
INSERT INTO Cities (ZipCode, Name) VALUES('5466', 'Asperup')
INSERT INTO Cities (ZipCode, Name) VALUES('5471', 'Søndersø')
INSERT INTO Cities (ZipCode, Name) VALUES('5474', 'Veflinge')
INSERT INTO Cities (ZipCode, Name) VALUES('5485', 'Skamby')
INSERT INTO Cities (ZipCode, Name) VALUES('5491', 'Blommenslyst')
INSERT INTO Cities (ZipCode, Name) VALUES('5492', 'Vissenbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('5500', 'Middelfart')
INSERT INTO Cities (ZipCode, Name) VALUES('5540', 'Ullerslev')
INSERT INTO Cities (ZipCode, Name) VALUES('5550', 'Langeskov')
INSERT INTO Cities (ZipCode, Name) VALUES('5560', 'Aarup')
INSERT INTO Cities (ZipCode, Name) VALUES('5580', 'Nørre Aaby')
INSERT INTO Cities (ZipCode, Name) VALUES('5591', 'Gelsted')
INSERT INTO Cities (ZipCode, Name) VALUES('5592', 'Ejby')
INSERT INTO Cities (ZipCode, Name) VALUES('5600', 'Faaborg')
INSERT INTO Cities (ZipCode, Name) VALUES('5601', 'Lyø')
INSERT INTO Cities (ZipCode, Name) VALUES('5602', 'Avernakø')
INSERT INTO Cities (ZipCode, Name) VALUES('5603', 'Bjørnø')
INSERT INTO Cities (ZipCode, Name) VALUES('5610', 'Assens')
INSERT INTO Cities (ZipCode, Name) VALUES('5620', 'Glamsbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('5631', 'Ebberup')
INSERT INTO Cities (ZipCode, Name) VALUES('5642', 'Millinge')
INSERT INTO Cities (ZipCode, Name) VALUES('5672', 'Broby')
INSERT INTO Cities (ZipCode, Name) VALUES('5683', 'Haarby')
INSERT INTO Cities (ZipCode, Name) VALUES('5690', 'Tommerup')
INSERT INTO Cities (ZipCode, Name) VALUES('5700', 'Svendborg')
INSERT INTO Cities (ZipCode, Name) VALUES('5750', 'Ringe')
INSERT INTO Cities (ZipCode, Name) VALUES('5762', 'Vester Skerninge')
INSERT INTO Cities (ZipCode, Name) VALUES('5771', 'Stenstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('5772', 'Kværndrup')
INSERT INTO Cities (ZipCode, Name) VALUES('5792', 'Årslev')
INSERT INTO Cities (ZipCode, Name) VALUES('5800', 'Nyborg')
INSERT INTO Cities (ZipCode, Name) VALUES('5853', 'Ørbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('5854', 'Gislev')
INSERT INTO Cities (ZipCode, Name) VALUES('5856', 'Ryslinge')
INSERT INTO Cities (ZipCode, Name) VALUES('5863', 'Ferritslev Fyn')
INSERT INTO Cities (ZipCode, Name) VALUES('5871', 'Frørup')
INSERT INTO Cities (ZipCode, Name) VALUES('5874', 'Hesselager')
INSERT INTO Cities (ZipCode, Name) VALUES('5881', 'Skårup Fyn')
INSERT INTO Cities (ZipCode, Name) VALUES('5882', 'Vejstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('5883', 'Oure')
INSERT INTO Cities (ZipCode, Name) VALUES('5884', 'Gudme')
INSERT INTO Cities (ZipCode, Name) VALUES('5892', 'Gudbjerg Sydfyn')
INSERT INTO Cities (ZipCode, Name) VALUES('5900', 'Rudkøbing')
INSERT INTO Cities (ZipCode, Name) VALUES('5932', 'Humble')
INSERT INTO Cities (ZipCode, Name) VALUES('5935', 'Bagenkop')
INSERT INTO Cities (ZipCode, Name) VALUES('5943', 'Strynø')
INSERT INTO Cities (ZipCode, Name) VALUES('5953', 'Tranekær')
INSERT INTO Cities (ZipCode, Name) VALUES('5960', 'Marstal')
INSERT INTO Cities (ZipCode, Name) VALUES('5965', 'Birkholm')
INSERT INTO Cities (ZipCode, Name) VALUES('5970', 'Ærøskøbing')
INSERT INTO Cities (ZipCode, Name) VALUES('5985', 'Søby Ærø')
INSERT INTO Cities (ZipCode, Name) VALUES('6000', 'Kolding')
INSERT INTO Cities (ZipCode, Name) VALUES('6040', 'Egtved')
INSERT INTO Cities (ZipCode, Name) VALUES('6051', 'Almind')
INSERT INTO Cities (ZipCode, Name) VALUES('6052', 'Viuf')
INSERT INTO Cities (ZipCode, Name) VALUES('6064', 'Jordrup')
INSERT INTO Cities (ZipCode, Name) VALUES('6070', 'Christiansfeld')
INSERT INTO Cities (ZipCode, Name) VALUES('6091', 'Bjert')
INSERT INTO Cities (ZipCode, Name) VALUES('6092', 'Sønder Stenderup')
INSERT INTO Cities (ZipCode, Name) VALUES('6093', 'Sjølund')
INSERT INTO Cities (ZipCode, Name) VALUES('6094', 'Hejls')
INSERT INTO Cities (ZipCode, Name) VALUES('6100', 'Haderslev')
INSERT INTO Cities (ZipCode, Name) VALUES('6200', 'Aabenraa')
INSERT INTO Cities (ZipCode, Name) VALUES('6210', 'Barsø')
INSERT INTO Cities (ZipCode, Name) VALUES('6230', 'Rødekro')
INSERT INTO Cities (ZipCode, Name) VALUES('6240', 'Løgumkloster')
INSERT INTO Cities (ZipCode, Name) VALUES('6261', 'Bredebro')
INSERT INTO Cities (ZipCode, Name) VALUES('6270', 'Tønder')
INSERT INTO Cities (ZipCode, Name) VALUES('6280', 'Højer')
INSERT INTO Cities (ZipCode, Name) VALUES('6300', 'Gråsten')
INSERT INTO Cities (ZipCode, Name) VALUES('6310', 'Broager')
INSERT INTO Cities (ZipCode, Name) VALUES('6320', 'Egernsund')
INSERT INTO Cities (ZipCode, Name) VALUES('6330', 'Padborg')
INSERT INTO Cities (ZipCode, Name) VALUES('6340', 'Kruså')
INSERT INTO Cities (ZipCode, Name) VALUES('6360', 'Tinglev')
INSERT INTO Cities (ZipCode, Name) VALUES('6372', 'Bylderup-Bov')
INSERT INTO Cities (ZipCode, Name) VALUES('6392', 'Bolderslev')
INSERT INTO Cities (ZipCode, Name) VALUES('6400', 'Sønderborg')
INSERT INTO Cities (ZipCode, Name) VALUES('6430', 'Nordborg')
INSERT INTO Cities (ZipCode, Name) VALUES('6440', 'Augustenborg')
INSERT INTO Cities (ZipCode, Name) VALUES('6470', 'Sydals')
INSERT INTO Cities (ZipCode, Name) VALUES('6500', 'Vojens')
INSERT INTO Cities (ZipCode, Name) VALUES('6510', 'Gram')
INSERT INTO Cities (ZipCode, Name) VALUES('6520', 'Toftlund')
INSERT INTO Cities (ZipCode, Name) VALUES('6534', 'Agerskov')
INSERT INTO Cities (ZipCode, Name) VALUES('6535', 'Branderup J')
INSERT INTO Cities (ZipCode, Name) VALUES('6541', 'Bevtoft')
INSERT INTO Cities (ZipCode, Name) VALUES('6560', 'Sommersted')
INSERT INTO Cities (ZipCode, Name) VALUES('6580', 'Vamdrup')
INSERT INTO Cities (ZipCode, Name) VALUES('6600', 'Vejen')
INSERT INTO Cities (ZipCode, Name) VALUES('6621', 'Gesten')
INSERT INTO Cities (ZipCode, Name) VALUES('6622', 'Bække')
INSERT INTO Cities (ZipCode, Name) VALUES('6623', 'Vorbasse')
INSERT INTO Cities (ZipCode, Name) VALUES('6630', 'Rødding')
INSERT INTO Cities (ZipCode, Name) VALUES('6640', 'Lunderskov')
INSERT INTO Cities (ZipCode, Name) VALUES('6650', 'Brørup')
INSERT INTO Cities (ZipCode, Name) VALUES('6660', 'Lintrup')
INSERT INTO Cities (ZipCode, Name) VALUES('6670', 'Holsted')
INSERT INTO Cities (ZipCode, Name) VALUES('6682', 'Hovborg')
INSERT INTO Cities (ZipCode, Name) VALUES('6683', 'Føvling')
INSERT INTO Cities (ZipCode, Name) VALUES('6690', 'Gørding')
INSERT INTO Cities (ZipCode, Name) VALUES('6700', 'Esbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('6701', 'Esbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('6705', 'Esbjerg Ø')
INSERT INTO Cities (ZipCode, Name) VALUES('6710', 'Esbjerg V')
INSERT INTO Cities (ZipCode, Name) VALUES('6715', 'Esbjerg N')
INSERT INTO Cities (ZipCode, Name) VALUES('6720', 'Fanø')
INSERT INTO Cities (ZipCode, Name) VALUES('6731', 'Tjæreborg')
INSERT INTO Cities (ZipCode, Name) VALUES('6740', 'Bramming')
INSERT INTO Cities (ZipCode, Name) VALUES('6752', 'Glejbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('6753', 'Agerbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('6760', 'Ribe')
INSERT INTO Cities (ZipCode, Name) VALUES('6771', 'Gredstedbro')
INSERT INTO Cities (ZipCode, Name) VALUES('6780', 'Skærbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('6792', 'Rømø')
INSERT INTO Cities (ZipCode, Name) VALUES('6800', 'Varde')
INSERT INTO Cities (ZipCode, Name) VALUES('6818', 'Årre')
INSERT INTO Cities (ZipCode, Name) VALUES('6823', 'Ansager')
INSERT INTO Cities (ZipCode, Name) VALUES('6830', 'Nørre Nebel')
INSERT INTO Cities (ZipCode, Name) VALUES('6840', 'Oksbøl')
INSERT INTO Cities (ZipCode, Name) VALUES('6851', 'Janderup Vestj')
INSERT INTO Cities (ZipCode, Name) VALUES('6852', 'Billum')
INSERT INTO Cities (ZipCode, Name) VALUES('6853', 'Vejers Strand')
INSERT INTO Cities (ZipCode, Name) VALUES('6854', 'Henne')
INSERT INTO Cities (ZipCode, Name) VALUES('6855', 'Outrup')
INSERT INTO Cities (ZipCode, Name) VALUES('6857', 'Blåvand')
INSERT INTO Cities (ZipCode, Name) VALUES('6862', 'Tistrup')
INSERT INTO Cities (ZipCode, Name) VALUES('6870', 'Ølgod')
INSERT INTO Cities (ZipCode, Name) VALUES('6880', 'Tarm')
INSERT INTO Cities (ZipCode, Name) VALUES('6893', 'Hemmet')
INSERT INTO Cities (ZipCode, Name) VALUES('6900', 'Skjern')
INSERT INTO Cities (ZipCode, Name) VALUES('6920', 'Videbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('6933', 'Kibæk')
INSERT INTO Cities (ZipCode, Name) VALUES('6940', 'Lem St')
INSERT INTO Cities (ZipCode, Name) VALUES('6950', 'Ringkøbing')
INSERT INTO Cities (ZipCode, Name) VALUES('6960', 'Hvide Sande')
INSERT INTO Cities (ZipCode, Name) VALUES('6971', 'Spjald')
INSERT INTO Cities (ZipCode, Name) VALUES('6973', 'Ørnhøj')
INSERT INTO Cities (ZipCode, Name) VALUES('6980', 'Tim')
INSERT INTO Cities (ZipCode, Name) VALUES('6990', 'Ulfborg')
INSERT INTO Cities (ZipCode, Name) VALUES('7000', 'Fredericia')
INSERT INTO Cities (ZipCode, Name) VALUES('7007', 'Fredericia')
INSERT INTO Cities (ZipCode, Name) VALUES('7017', 'Taulov Pakkecenter')
INSERT INTO Cities (ZipCode, Name) VALUES('7018', 'Pakker TLP')
INSERT INTO Cities (ZipCode, Name) VALUES('7029', 'Fredericia')
INSERT INTO Cities (ZipCode, Name) VALUES('7080', 'Børkop')
INSERT INTO Cities (ZipCode, Name) VALUES('7100', 'Vejle')
INSERT INTO Cities (ZipCode, Name) VALUES('7120', 'Vejle Øst')
INSERT INTO Cities (ZipCode, Name) VALUES('7130', 'Juelsminde')
INSERT INTO Cities (ZipCode, Name) VALUES('7140', 'Stouby')
INSERT INTO Cities (ZipCode, Name) VALUES('7150', 'Barrit')
INSERT INTO Cities (ZipCode, Name) VALUES('7160', 'Tørring')
INSERT INTO Cities (ZipCode, Name) VALUES('7171', 'Uldum')
INSERT INTO Cities (ZipCode, Name) VALUES('7173', 'Vonge')
INSERT INTO Cities (ZipCode, Name) VALUES('7182', 'Bredsten')
INSERT INTO Cities (ZipCode, Name) VALUES('7183', 'Randbøl')
INSERT INTO Cities (ZipCode, Name) VALUES('7184', 'Vandel')
INSERT INTO Cities (ZipCode, Name) VALUES('7190', 'Billund')
INSERT INTO Cities (ZipCode, Name) VALUES('7200', 'Grindsted')
INSERT INTO Cities (ZipCode, Name) VALUES('7250', 'Hejnsvig')
INSERT INTO Cities (ZipCode, Name) VALUES('7260', 'Sønder Omme')
INSERT INTO Cities (ZipCode, Name) VALUES('7270', 'Stakroge')
INSERT INTO Cities (ZipCode, Name) VALUES('7280', 'Sønder Felding')
INSERT INTO Cities (ZipCode, Name) VALUES('7300', 'Jelling')
INSERT INTO Cities (ZipCode, Name) VALUES('7321', 'Gadbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('7323', 'Give')
INSERT INTO Cities (ZipCode, Name) VALUES('7330', 'Brande')
INSERT INTO Cities (ZipCode, Name) VALUES('7361', 'Ejstrupholm')
INSERT INTO Cities (ZipCode, Name) VALUES('7362', 'Hampen')
INSERT INTO Cities (ZipCode, Name) VALUES('7400', 'Herning')
INSERT INTO Cities (ZipCode, Name) VALUES('7429', 'Herning')
INSERT INTO Cities (ZipCode, Name) VALUES('7430', 'Ikast')
INSERT INTO Cities (ZipCode, Name) VALUES('7441', 'Bording')
INSERT INTO Cities (ZipCode, Name) VALUES('7442', 'Engesvang')
INSERT INTO Cities (ZipCode, Name) VALUES('7451', 'Sunds')
INSERT INTO Cities (ZipCode, Name) VALUES('7470', 'Karup J')
INSERT INTO Cities (ZipCode, Name) VALUES('7480', 'Vildbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('7490', 'Aulum')
INSERT INTO Cities (ZipCode, Name) VALUES('7500', 'Holstebro')
INSERT INTO Cities (ZipCode, Name) VALUES('7540', 'Haderup')
INSERT INTO Cities (ZipCode, Name) VALUES('7550', 'Sørvad')
INSERT INTO Cities (ZipCode, Name) VALUES('7560', 'Hjerm')
INSERT INTO Cities (ZipCode, Name) VALUES('7570', 'Vemb')
INSERT INTO Cities (ZipCode, Name) VALUES('7600', 'Struer')
INSERT INTO Cities (ZipCode, Name) VALUES('7620', 'Lemvig')
INSERT INTO Cities (ZipCode, Name) VALUES('7650', 'Bøvlingbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('7660', 'Bækmarksbro')
INSERT INTO Cities (ZipCode, Name) VALUES('7673', 'Harboøre')
INSERT INTO Cities (ZipCode, Name) VALUES('7680', 'Thyborøn')
INSERT INTO Cities (ZipCode, Name) VALUES('7700', 'Thisted')
INSERT INTO Cities (ZipCode, Name) VALUES('7730', 'Hanstholm')
INSERT INTO Cities (ZipCode, Name) VALUES('7741', 'Frøstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('7742', 'Vesløs')
INSERT INTO Cities (ZipCode, Name) VALUES('7752', 'Snedsted')
INSERT INTO Cities (ZipCode, Name) VALUES('7755', 'Bedsted Thy')
INSERT INTO Cities (ZipCode, Name) VALUES('7760', 'Hurup Thy')
INSERT INTO Cities (ZipCode, Name) VALUES('7770', 'Vestervig')
INSERT INTO Cities (ZipCode, Name) VALUES('7790', 'Thyholm')
INSERT INTO Cities (ZipCode, Name) VALUES('7800', 'Skive')
INSERT INTO Cities (ZipCode, Name) VALUES('7830', 'Vinderup')
INSERT INTO Cities (ZipCode, Name) VALUES('7840', 'Højslev')
INSERT INTO Cities (ZipCode, Name) VALUES('7850', 'Stoholm Jyll')
INSERT INTO Cities (ZipCode, Name) VALUES('7860', 'Spøttrup')
INSERT INTO Cities (ZipCode, Name) VALUES('7870', 'Roslev')
INSERT INTO Cities (ZipCode, Name) VALUES('7884', 'Fur')
INSERT INTO Cities (ZipCode, Name) VALUES('7900', 'Nykøbing M')
INSERT INTO Cities (ZipCode, Name) VALUES('7950', 'Erslev')
INSERT INTO Cities (ZipCode, Name) VALUES('7960', 'Karby')
INSERT INTO Cities (ZipCode, Name) VALUES('7970', 'Redsted M')
INSERT INTO Cities (ZipCode, Name) VALUES('7980', 'Vils')
INSERT INTO Cities (ZipCode, Name) VALUES('7990', 'Øster Assels')
INSERT INTO Cities (ZipCode, Name) VALUES('7992', 'Sydjylland/Fyn USF P')
INSERT INTO Cities (ZipCode, Name) VALUES('7993', 'Sydjylland/Fyn USF B')
INSERT INTO Cities (ZipCode, Name) VALUES('7996', 'Fakturaservice')
INSERT INTO Cities (ZipCode, Name) VALUES('7997', 'Fakturascanning')
INSERT INTO Cities (ZipCode, Name) VALUES('7998', 'Statsservice')
INSERT INTO Cities (ZipCode, Name) VALUES('7999', 'Kommunepost')
INSERT INTO Cities (ZipCode, Name) VALUES('8000', 'Aarhus C')
INSERT INTO Cities (ZipCode, Name) VALUES('8100', 'Aarhus C')
INSERT INTO Cities (ZipCode, Name) VALUES('8200', 'Aarhus N')
INSERT INTO Cities (ZipCode, Name) VALUES('8210', 'Aarhus V')
INSERT INTO Cities (ZipCode, Name) VALUES('8220', 'Brabrand')
INSERT INTO Cities (ZipCode, Name) VALUES('8229', 'Risskov Ø')
INSERT INTO Cities (ZipCode, Name) VALUES('8230', 'Åbyhøj')
INSERT INTO Cities (ZipCode, Name) VALUES('8240', 'Risskov')
INSERT INTO Cities (ZipCode, Name) VALUES('8245', 'Risskov Ø')
INSERT INTO Cities (ZipCode, Name) VALUES('8250', 'Egå')
INSERT INTO Cities (ZipCode, Name) VALUES('8260', 'Viby J')
INSERT INTO Cities (ZipCode, Name) VALUES('8270', 'Højbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('8300', 'Odder')
INSERT INTO Cities (ZipCode, Name) VALUES('8305', 'Samsø')
INSERT INTO Cities (ZipCode, Name) VALUES('8310', 'Tranbjerg J')
INSERT INTO Cities (ZipCode, Name) VALUES('8320', 'Mårslet')
INSERT INTO Cities (ZipCode, Name) VALUES('8330', 'Beder')
INSERT INTO Cities (ZipCode, Name) VALUES('8340', 'Malling')
INSERT INTO Cities (ZipCode, Name) VALUES('8350', 'Hundslund')
INSERT INTO Cities (ZipCode, Name) VALUES('8355', 'Solbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('8361', 'Hasselager')
INSERT INTO Cities (ZipCode, Name) VALUES('8362', 'Hørning')
INSERT INTO Cities (ZipCode, Name) VALUES('8370', 'Hadsten')
INSERT INTO Cities (ZipCode, Name) VALUES('8380', 'Trige')
INSERT INTO Cities (ZipCode, Name) VALUES('8381', 'Tilst')
INSERT INTO Cities (ZipCode, Name) VALUES('8382', 'Hinnerup')
INSERT INTO Cities (ZipCode, Name) VALUES('8400', 'Ebeltoft')
INSERT INTO Cities (ZipCode, Name) VALUES('8410', 'Rønde')
INSERT INTO Cities (ZipCode, Name) VALUES('8420', 'Knebel')
INSERT INTO Cities (ZipCode, Name) VALUES('8444', 'Balle')
INSERT INTO Cities (ZipCode, Name) VALUES('8450', 'Hammel')
INSERT INTO Cities (ZipCode, Name) VALUES('8462', 'Harlev J')
INSERT INTO Cities (ZipCode, Name) VALUES('8464', 'Galten')
INSERT INTO Cities (ZipCode, Name) VALUES('8471', 'Sabro')
INSERT INTO Cities (ZipCode, Name) VALUES('8472', 'Sporup')
INSERT INTO Cities (ZipCode, Name) VALUES('8500', 'Grenaa')
INSERT INTO Cities (ZipCode, Name) VALUES('8520', 'Lystrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8530', 'Hjortshøj')
INSERT INTO Cities (ZipCode, Name) VALUES('8541', 'Skødstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8543', 'Hornslet')
INSERT INTO Cities (ZipCode, Name) VALUES('8544', 'Mørke')
INSERT INTO Cities (ZipCode, Name) VALUES('8550', 'Ryomgård')
INSERT INTO Cities (ZipCode, Name) VALUES('8560', 'Kolind')
INSERT INTO Cities (ZipCode, Name) VALUES('8570', 'Trustrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8581', 'Nimtofte')
INSERT INTO Cities (ZipCode, Name) VALUES('8585', 'Glesborg')
INSERT INTO Cities (ZipCode, Name) VALUES('8586', 'Ørum Djurs')
INSERT INTO Cities (ZipCode, Name) VALUES('8592', 'Anholt')
INSERT INTO Cities (ZipCode, Name) VALUES('8600', 'Silkeborg')
INSERT INTO Cities (ZipCode, Name) VALUES('8620', 'Kjellerup')
INSERT INTO Cities (ZipCode, Name) VALUES('8632', 'Lemming')
INSERT INTO Cities (ZipCode, Name) VALUES('8641', 'Sorring')
INSERT INTO Cities (ZipCode, Name) VALUES('8643', 'Ans By')
INSERT INTO Cities (ZipCode, Name) VALUES('8653', 'Them')
INSERT INTO Cities (ZipCode, Name) VALUES('8654', 'Bryrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8660', 'Skanderborg')
INSERT INTO Cities (ZipCode, Name) VALUES('8670', 'Låsby')
INSERT INTO Cities (ZipCode, Name) VALUES('8680', 'Ry')
INSERT INTO Cities (ZipCode, Name) VALUES('8700', 'Horsens')
INSERT INTO Cities (ZipCode, Name) VALUES('8721', 'Daugård')
INSERT INTO Cities (ZipCode, Name) VALUES('8722', 'Hedensted')
INSERT INTO Cities (ZipCode, Name) VALUES('8723', 'Løsning')
INSERT INTO Cities (ZipCode, Name) VALUES('8732', 'Hovedgård')
INSERT INTO Cities (ZipCode, Name) VALUES('8740', 'Brædstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8751', 'Gedved')
INSERT INTO Cities (ZipCode, Name) VALUES('8752', 'Østbirk')
INSERT INTO Cities (ZipCode, Name) VALUES('8762', 'Flemming')
INSERT INTO Cities (ZipCode, Name) VALUES('8763', 'Rask Mølle')
INSERT INTO Cities (ZipCode, Name) VALUES('8765', 'Klovborg')
INSERT INTO Cities (ZipCode, Name) VALUES('8766', 'Nørre Snede')
INSERT INTO Cities (ZipCode, Name) VALUES('8781', 'Stenderup')
INSERT INTO Cities (ZipCode, Name) VALUES('8783', 'Hornsyld')
INSERT INTO Cities (ZipCode, Name) VALUES('8789', 'Endelave')
INSERT INTO Cities (ZipCode, Name) VALUES('8799', 'Tunø')
INSERT INTO Cities (ZipCode, Name) VALUES('8800', 'Viborg')
INSERT INTO Cities (ZipCode, Name) VALUES('8830', 'Tjele')
INSERT INTO Cities (ZipCode, Name) VALUES('8831', 'Løgstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8832', 'Skals')
INSERT INTO Cities (ZipCode, Name) VALUES('8840', 'Rødkærsbro')
INSERT INTO Cities (ZipCode, Name) VALUES('8850', 'Bjerringbro')
INSERT INTO Cities (ZipCode, Name) VALUES('8860', 'Ulstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8870', 'Langå')
INSERT INTO Cities (ZipCode, Name) VALUES('8881', 'Thorsø')
INSERT INTO Cities (ZipCode, Name) VALUES('8882', 'Fårvang')
INSERT INTO Cities (ZipCode, Name) VALUES('8883', 'Gjern')
INSERT INTO Cities (ZipCode, Name) VALUES('8900', 'Randers C')
INSERT INTO Cities (ZipCode, Name) VALUES('8920', 'Randers NV')
INSERT INTO Cities (ZipCode, Name) VALUES('8930', 'Randers NØ')
INSERT INTO Cities (ZipCode, Name) VALUES('8940', 'Randers SV')
INSERT INTO Cities (ZipCode, Name) VALUES('8950', 'Ørsted')
INSERT INTO Cities (ZipCode, Name) VALUES('8960', 'Randers SØ')
INSERT INTO Cities (ZipCode, Name) VALUES('8961', 'Allingåbro')
INSERT INTO Cities (ZipCode, Name) VALUES('8963', 'Auning')
INSERT INTO Cities (ZipCode, Name) VALUES('8970', 'Havndal')
INSERT INTO Cities (ZipCode, Name) VALUES('8981', 'Spentrup')
INSERT INTO Cities (ZipCode, Name) VALUES('8983', 'Gjerlev J')
INSERT INTO Cities (ZipCode, Name) VALUES('8990', 'Fårup')
INSERT INTO Cities (ZipCode, Name) VALUES('9000', 'Aalborg')
INSERT INTO Cities (ZipCode, Name) VALUES('9029', 'Aalborg')
INSERT INTO Cities (ZipCode, Name) VALUES('9100', 'Aalborg')
INSERT INTO Cities (ZipCode, Name) VALUES('9200', 'Aalborg SV')
INSERT INTO Cities (ZipCode, Name) VALUES('9210', 'Aalborg SØ')
INSERT INTO Cities (ZipCode, Name) VALUES('9220', 'Aalborg Øst')
INSERT INTO Cities (ZipCode, Name) VALUES('9230', 'Svenstrup J')
INSERT INTO Cities (ZipCode, Name) VALUES('9240', 'Nibe')
INSERT INTO Cities (ZipCode, Name) VALUES('9260', 'Gistrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9270', 'Klarup')
INSERT INTO Cities (ZipCode, Name) VALUES('9280', 'Storvorde')
INSERT INTO Cities (ZipCode, Name) VALUES('9293', 'Kongerslev')
INSERT INTO Cities (ZipCode, Name) VALUES('9300', 'Sæby')
INSERT INTO Cities (ZipCode, Name) VALUES('9310', 'Vodskov')
INSERT INTO Cities (ZipCode, Name) VALUES('9320', 'Hjallerup')
INSERT INTO Cities (ZipCode, Name) VALUES('9330', 'Dronninglund')
INSERT INTO Cities (ZipCode, Name) VALUES('9340', 'Asaa')
INSERT INTO Cities (ZipCode, Name) VALUES('9352', 'Dybvad')
INSERT INTO Cities (ZipCode, Name) VALUES('9362', 'Gandrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9370', 'Hals')
INSERT INTO Cities (ZipCode, Name) VALUES('9380', 'Vestbjerg')
INSERT INTO Cities (ZipCode, Name) VALUES('9381', 'Sulsted')
INSERT INTO Cities (ZipCode, Name) VALUES('9382', 'Tylstrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9400', 'Nørresundby')
INSERT INTO Cities (ZipCode, Name) VALUES('9430', 'Vadum')
INSERT INTO Cities (ZipCode, Name) VALUES('9440', 'Aabybro')
INSERT INTO Cities (ZipCode, Name) VALUES('9460', 'Brovst')
INSERT INTO Cities (ZipCode, Name) VALUES('9480', 'Løkken')
INSERT INTO Cities (ZipCode, Name) VALUES('9490', 'Pandrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9492', 'Blokhus')
INSERT INTO Cities (ZipCode, Name) VALUES('9493', 'Saltum')
INSERT INTO Cities (ZipCode, Name) VALUES('9500', 'Hobro')
INSERT INTO Cities (ZipCode, Name) VALUES('9510', 'Arden')
INSERT INTO Cities (ZipCode, Name) VALUES('9520', 'Skørping')
INSERT INTO Cities (ZipCode, Name) VALUES('9530', 'Støvring')
INSERT INTO Cities (ZipCode, Name) VALUES('9541', 'Suldrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9550', 'Mariager')
INSERT INTO Cities (ZipCode, Name) VALUES('9560', 'Hadsund')
INSERT INTO Cities (ZipCode, Name) VALUES('9574', 'Bælum')
INSERT INTO Cities (ZipCode, Name) VALUES('9575', 'Terndrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9600', 'Aars')
INSERT INTO Cities (ZipCode, Name) VALUES('9610', 'Nørager')
INSERT INTO Cities (ZipCode, Name) VALUES('9620', 'Aalestrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9631', 'Gedsted')
INSERT INTO Cities (ZipCode, Name) VALUES('9632', 'Møldrup')
INSERT INTO Cities (ZipCode, Name) VALUES('9640', 'Farsø')
INSERT INTO Cities (ZipCode, Name) VALUES('9670', 'Løgstør')
INSERT INTO Cities (ZipCode, Name) VALUES('9681', 'Ranum')
INSERT INTO Cities (ZipCode, Name) VALUES('9690', 'Fjerritslev')
INSERT INTO Cities (ZipCode, Name) VALUES('9700', 'Brønderslev')
INSERT INTO Cities (ZipCode, Name) VALUES('9740', 'Jerslev J')
INSERT INTO Cities (ZipCode, Name) VALUES('9750', 'Østervrå')
INSERT INTO Cities (ZipCode, Name) VALUES('9760', 'Vrå')
INSERT INTO Cities (ZipCode, Name) VALUES('9800', 'Hjørring')
INSERT INTO Cities (ZipCode, Name) VALUES('9830', 'Tårs')
INSERT INTO Cities (ZipCode, Name) VALUES('9850', 'Hirtshals')
INSERT INTO Cities (ZipCode, Name) VALUES('9870', 'Sindal')
INSERT INTO Cities (ZipCode, Name) VALUES('9881', 'Bindslev')
INSERT INTO Cities (ZipCode, Name) VALUES('9900', 'Frederikshavn')
INSERT INTO Cities (ZipCode, Name) VALUES('9940', 'Læsø')
INSERT INTO Cities (ZipCode, Name) VALUES('9970', 'Strandby')
INSERT INTO Cities (ZipCode, Name) VALUES('9981', 'Jerup')
INSERT INTO Cities (ZipCode, Name) VALUES('9982', 'Ålbæk')
INSERT INTO Cities (ZipCode, Name) VALUES('9990', 'Skagen')