DROP TABLE IF EXISTS JobFiles
DROP TABLE IF EXISTS Files
DROP TABLE IF EXISTS Jobs
DROP TABLE IF EXISTS Stacks
DROP TABLE IF EXISTS MachineOperators
DROP TABLE IF EXISTS Machines
DROP TABLE IF EXISTS StatusCodes
DROP TABLE IF EXISTS UserPrivileges
DROP TABLE IF EXISTS DefaultPrivileges
DROP TABLE IF EXISTS Users
DROP TABLE IF EXISTS UserTypes
DROP TABLE IF EXISTS Privileges
DROP TABLE IF EXISTS Companies
DROP TABLE IF EXISTS Cities

CREATE TABLE Cities (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	ZipCode CHAR(4) NOT NULL
)

CREATE TABLE Companies (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(100) UNIQUE NOT NULL,
	Address VARCHAR(250) NOT NULL,
	CityId INT NOT NULL 
		FOREIGN KEY REFERENCES Cities(Id),
	Phone CHAR(8) UNIQUE,
	Email VARCHAR(100) UNIQUE,
	CreatedDate DATE DEFAULT GETDATE()
)

CREATE TABLE Privileges (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(250) NOT NULL
)

CREATE TABLE UserTypes (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Users (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Username VARCHAR(50) UNIQUE NOT NULL,
	UserTypeId INT NOT NULL
		FOREIGN KEY REFERENCES UserTypes(Id),
	CompanyId INT NOT NULL
		FOREIGN KEY REFERENCES Companies(Id),
	FirstName VARCHAR(50),
	LastName VARCHAR(50),
	Email VARCHAR(100) UNIQUE,
	CreatedDate DATE DEFAULT GETDATE(),
	LastActivity DATETIME2(0) DEFAULT GETDATE(),
	PasswordHash BINARY(64) NOT NULL,
	PasswordSalt BINARY(128) NOT NULL
)

CREATE TABLE DefaultPrivileges (
	PrivilegeId INT NOT NULL
		FOREIGN KEY REFERENCES Privileges(Id)
		ON DELETE CASCADE,
	UserTypeId INT NOT NULL
		FOREIGN KEY REFERENCES UserTypes(Id)
		ON DELETE CASCADE,
	PRIMARY KEY (PrivilegeId, UserTypeId)
)

CREATE TABLE UserPrivileges (
	PrivilegeId INT NOT NULL
		FOREIGN KEY REFERENCES Privileges(Id)
		ON DELETE CASCADE,
	UserId INT NOT NULL
		FOREIGN KEY REFERENCES Users(Id)
		ON DELETE CASCADE,
	PRIMARY KEY (PrivilegeId, UserId)
)

CREATE TABLE StatusCodes (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(250) NOT NULL,
	Type INT NOT NULL
)

CREATE TABLE Machines (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Location VARCHAR(250),
	CompanyId INT NOT NULL
		FOREIGN KEY REFERENCES Companies(Id),
	StatusCodeId INT NOT NULL
		FOREIGN KEY REFERENCES StatusCodes(Id),
	StatusChanged DATETIME2(0) DEFAULT GETDATE()
)

CREATE TABLE MachineOperators (
	UserId INT NOT NULL
		FOREIGN KEY REFERENCES Users(Id)
		ON DELETE CASCADE,
	MachineId INT NOT NULL
		FOREIGN KEY REFERENCES Machines(Id)
		ON DELETE CASCADE,
	PRIMARY KEY (UserId, MachineId)
)

CREATE TABLE Stacks (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	MachineId INT NOT NULL
		FOREIGN KEY REFERENCES Machines(Id)
		ON DELETE CASCADE,
	Priority INT NOT NULL,
	Description VARCHAR(250),
	CreatedTime DATETIME2(0) DEFAULT GETDATE(),
	IsFinished BIT
)

CREATE TABLE Jobs (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	StackId INT NOT NULL
		FOREIGN KEY REFERENCES Stacks(Id)
		ON DELETE CASCADE,
	Priority INT NOT NULL,
	Description VARCHAR(250),
	CreatedTime DATETIME2(0) DEFAULT GETDATE(),
	EstimatedTime DATETIME2(0) DEFAULT GETDATE(),
	StartedTime DATETIME2(0) DEFAULT GETDATE()
)

CREATE TABLE Files (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FileLocation VARCHAR(250) NOT NULL,
	UploadedTime DATETIME2(0) DEFAULT GETDATE(),
	FileType CHAR(3)
)

CREATE TABLE JobFiles (
	JobId INT NOT NULL
		FOREIGN KEY REFERENCES Jobs(Id)
		ON DELETE CASCADE,
	FileId INT NOT NULL
		FOREIGN KEY REFERENCES Files(Id)
		ON DELETE CASCADE,
	PRIMARY KEY (JobId, FileId)
)

INSERT INTO UserTypes VALUES ('S_Admin')
INSERT INTO UserTypes VALUES ('K_Admin')
INSERT INTO UserTypes VALUES ('K_Operator')

INSERT INTO StatusCodes VALUES ('Running', 'Machine is running', 1)
INSERT INTO StatusCodes VALUES ('Out of materials', 'Machine has run out of materials', 2)
INSERT INTO StatusCodes VALUES ('Unknown error', 'Machine has encountered an unknown problem and stopped working', 2)